<?php$GLOBALS['vhostproduct_cfg']['1']=array('id'=>'1','name'=>'phpmysql','web_quota'=>'100','db_quota'=>'100','templete'=>'php','price'=>'1000','pause_flag'=>'0','node'=>'node2','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'1','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'php52','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'1');$GLOBALS['vhostproduct_cfg']['2']=array('id'=>'2','name'=>'php','web_quota'=>'200','db_quota'=>'100','templete'=>'php','price'=>'0','pause_flag'=>'0','node'=>'node211','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'1','subdir'=>'','describe'=>'','domain'=>'20','subtemplete'=>'php52','upid'=>'0','htaccess'=>'1','max_connect'=>'2000','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'2048000','view'=>'1');
$GLOBALS['vhostproduct_cfg']['3']=array('id'=>'3','name'=>'sdd','web_quota'=>'100','db_quota'=>'0','templete'=>'php52','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['4']=array('id'=>'4','name'=>'jjjj','web_quota'=>'200','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['5']=array('id'=>'5','name'=>'lllllll','web_quota'=>'100','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['6']=array('id'=>'6','name'=>'oooooo','web_quota'=>'100','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['7']=array('id'=>'7','name'=>'ffffff','web_quota'=>'100','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['8']=array('id'=>'8','name'=>'yyyyy','web_quota'=>'100','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['9']=array('id'=>'9','name'=>'hhhhhhh','web_quota'=>'100','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['10']=array('id'=>'10','name'=>'vvvvvv','web_quota'=>'100','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['11']=array('id'=>'11','name'=>'dfgdfg','web_quota'=>'200','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['12']=array('id'=>'12','name'=>'mmmm','web_quota'=>'100','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['13']=array('id'=>'13','name'=>'mmmmm','web_quota'=>'100','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');
$GLOBALS['vhostproduct_cfg']['14']=array('id'=>'14','name'=>'sdfsadf','web_quota'=>'200','db_quota'=>'0','templete'=>'html','price'=>'0','pause_flag'=>'0','node'=>'node3','try_flag'=>'0','month_flag'=>'0','subdir_flag'=>'0','subdir'=>'','describe'=>'','domain'=>'-1','subtemplete'=>'','upid'=>'0','htaccess'=>'1','max_connect'=>'0','ftp'=>'1','log_file'=>'1','access'=>'1','speed_limit'=>'0','view'=>'0');?>